#!/usr/bin/env python3

import os
import sys
import shutil
import argparse

from pathlib import Path
from bs4 import BeautifulSoup
from subprocess import run, PIPE
from lib.utils import generate_index


def parse_args():
    parser = argparse.ArgumentParser(
        description='extract exception reports')
    parser.add_argument('reports', metavar='DIR', type=Path,
                        help='reports directory with an index.html')
    parser.add_argument('-o', '--output', metavar='DIR', type=Path,
                        default='exception-reports',
                        help='output to DIR (defualt: exception-reports)')
    return parser.parse_args()


if __name__ == '__main__':

    args = parse_args()
    index = args.reports / 'index.html'
    if not index.exists():
        print(f'"{index}" does not exist', file=sys.stderr)
        sys.exit(1)
    args.output.mkdir(exist_ok=True, parents=True)
    index = BeautifulSoup(index.read_text(), 'html.parser')
    reports = index.select('tr#exceptional a')
    for report in reports:
        report = args.reports / report['href'][:-len('#EndPath')]
        shutil.copy(report, args.output)
    print(f'Total of {len(reports)} exception report(s)')
    generate_index(args.output)
